version: '3.8'
services:
  langscout-ingest:
    build:
      dockerfile: Dockerfile.ingest
    image: langscout-ingest:local
    ports:
      - "1984:1984"
    env_file:
      - ./packages/ingest/.env
    depends_on:
      - langscout-mongodb

  langscout-mongodb:
    image: mongo:latest@sha256:da1dbe035f889c320be0fd3f113c76dd71c3a87bbfcfaee008d014e7ade17e3b
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --bind_ip_all
