FROM node:20.14.0-alpine3.19@sha256:acedb9b82ab6964a04329bf543c1d4692fbc75d255048c1665db90ab5026f753 AS base


FROM base AS deps

WORKDIR /app

# Copy root worksplace level package.json
COPY package.json package-lock.json ./
# Copy relevant packages for the api workspace
COPY ./packages/api ./packages/api
COPY ./packages/models ./packages/models
RUN npm ci --frozen-lockfile


FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
#COPY --from=deps /app/packages/api/node_modules ./node_modules
# Copy in packages/models as this is simlinked in package.json. npm workspaces...sigh
COPY --from=deps /app/packages/models ./packages/models
COPY ./packages/api/src ./src
COPY ./packages/api/tsconfig.json ./
COPY ./packages/api/package.json ./

RUN npm run build

FROM base AS runner

WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 express

COPY --from=builder --chown=express:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=express:nodejs /app/dist ./

USER express

EXPOSE 1994
ENV PORT 1994

ENV HOSTNAME "0.0.0.0"

CMD ["node", "index.js"]
