version: '3.8'
services:
  langtrace-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: langtrace-ui:local
    ports:
      - "3000:3000"
    environment:
      - LANGTRACE_API_URL=http://langtrace-api:1994
    depends_on:
      - langtrace-api

  langtrace-ingest:
    build:
      context: ./server
      dockerfile: Dockerfile.ingest
    image: langtrace-ingest:local
    ports:
      - "1984:1984"
    environment:
      - MONGODB_ATLAS_CLUSTER_URI=mongodb+srv://george:xMnLtjtgXHugGqYP@capgpt.fwnm8.mongodb.net/?retryWrites=true&w=majority
      - MONGODB_DB_NAME=capgpt
      - MONGODB_TRACE_COLLECTION_NAME=traces

  langtrace-api:
    build:
      context: ./server
      dockerfile: Dockerfile.langtrace
    image: langtrace-api:local
    ports:
      - "1994:1994"
    environment:
      - MONGODB_ATLAS_CLUSTER_URI=mongodb+srv://george:xMnLtjtgXHugGqYP@capgpt.fwnm8.mongodb.net/?retryWrites=true&w=majority
      - MONGODB_DB_NAME=capgpt
      - MONGODB_TRACE_COLLECTION_NAME=traces
