FROM node:20.12.2-alpine3.19@sha256:ec0c413b1d84f3f7f67ec986ba885930c57b5318d2eb3abc6960ee05d4f2eb28 AS base


FROM base AS deps

WORKDIR /app

# Copy root worksplace level package.json
COPY package.json package-lock.json ./
# Copy relevant packages for the ingest workspace
COPY ./packages/ingest ./packages/ingest
COPY ./packages/models ./packages/models
RUN npm ci --frozen-lockfile


FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
#COPY --from=deps /app/packages/ingest/node_modules ./node_modules
# Copy in packages/models as this is simlinked in package.json. npm workspaces...sigh
COPY --from=deps /app/packages/models ./packages/models
COPY ./packages/ingest/src ./src
COPY ./packages/ingest/tsconfig.json ./
COPY ./packages/ingest/package.json ./

RUN npm run build

FROM base AS runner

WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 express

COPY --from=builder --chown=express:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=express:nodejs /app/dist ./

USER express

EXPOSE 1984
ENV PORT 1984

ENV HOSTNAME "0.0.0.0"

CMD ["node", "index.js"]
