version: '3.8'
services:
  langtrace-ingest:
    build:
      dockerfile: Dockerfile.ingest
    image: langtrace-ingest:local
    ports:
      - "1984:1984"
    env_file:
      - ./packages/ingest/.env
