# Stage 1: Build
FROM node:20-alpine@sha256:c0a3badbd8a0a760de903e00cedbca94588e609299820557e72cba2a53dbaa2c AS build

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy only necessary source files (adjust as per your project structure)
COPY . .

# Build your application here if necessary
# RUN npm run build

# Stage 2: Final Image
FROM node:20-alpine@sha256:c0a3badbd8a0a760de903e00cedbca94588e609299820557e72cba2a53dbaa2c

WORKDIR /app

# Copy necessary files from build stage
COPY --from=build /app /app

# Expose the port the app runs on
EXPOSE 1994

# Start your app
CMD ["npm", "run", "start:langtrace"]
