# Stage 1: Build
FROM node:20-alpine@sha256:f3299f16246c71ab8b304d6745bb4059fa9283e8d025972e28436a9f9b36ed24 AS build

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy only necessary source files (adjust as per your project structure)
COPY . .

# Build your application here if necessary
# RUN npm run build

# Stage 2: Final Image
FROM node:20-alpine@sha256:f3299f16246c71ab8b304d6745bb4059fa9283e8d025972e28436a9f9b36ed24

WORKDIR /app

# Copy necessary files from build stage
COPY --from=build /app /app

# Expose the port the app runs on
EXPOSE 1994

# Start your app
CMD ["npm", "run", "start:langtrace"]
