name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run audit
        run: npm audit
      - name: Run lint
        run: npm run lint --workspaces
      - name: Build
        run: npm run build --workspaces
        env:
          LANGTRACE_API_URL: "http://localhost:1994"
      - name: Test
        run: npm run test --workspaces
