name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ui, server]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.project }}
      - name: Run lint
        run: npm run lint
        working-directory: ${{ matrix.project }}
      - name: Build
        run: npm run build
        working-directory: ${{ matrix.project }}
