name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run audit
        run: npm audit
      - name: Run lint
        run: npm run lint --workspaces
      - name: Build
        run: npm run build --workspaces
        env:
          LANGSCOUT_API_URL: "http://localhost:1994"
      - name: Test
        run: npm run test --workspaces
